### ISSUE TITLE
amlvm-snapshot exited with status 1

### ISSUE THREAD

**Issue by xaz123** [marxarelli/amlvm-snapshot#3] opened 2011-02-09 21:31 UTC
I am trying to use amlvm-snapshot to do Linux LVM snapshot backup. But keep getting errors in amanda backup report. the relevant content is as follows:

STRANGE DUMP DETAILS:
  /-- client-host-name / lev 0 STRANGE
  |
  ? Script 'amlvm-snapshot' command 'PRE-DLE-BACKUP' exited with status 1: see /var/log/amanda/client/daily/sendbackup.20110209144442.debug
  sendbackup: info BACKUP=APPLICATION
  sendbackup: info APPLICATION=amgtar
  sendbackup: info RECOVER_CMD=/usr/bin/gzip -dc |/usr/libexec/amanda/application/amgtar restore [./file-to-restore]+
  sendbackup: info COMPRESS_SUFFIX=.gz
  sendbackup: info end
  ? /bin/gtar: ./fe/logs/error_log: file changed as we read it
  | /bin/gtar: ./tmp/.font-unix/fs7100: socket ignored
  | /bin/gtar: ./tmp/ssh-SFTrOp3063/agent.3063: socket ignored
  | /bin/gtar: ./var/run/acpid.socket: socket ignored
  | /bin/gtar: ./var/run/audispd_events: socket ignored
  | /bin/gtar: ./var/run/pcscd.comm: socket ignored
  | /bin/gtar: ./var/run/avahi-daemon/socket: socket ignored
  | /bin/gtar: ./var/run/dbus/system_bus_socket: socket ignored
  | /bin/gtar: ./var/run/nscd/socket: socket ignored
  | Total bytes written: 3300454400 (3.1GiB, 12MiB/s)
  sendbackup: size 3223100
  sendbackup: end
  |
  ? Script 'amlvm-snapshot' command 'POST-DLE-BACKUP' exited with status 1: see /var/log/amanda/client/daily/sendbackup.20110209144442.debug
  --------
  /-- client-host-name /boot lev 1 STRANGE
  |
  ? Script 'amlvm-snapshot' command 'PRE-DLE-BACKUP' exited with status 1: see /var/log/amanda/client/daily/sendbackup.20110209144427.debug
  sendbackup: info BACKUP=APPLICATION
  sendbackup: info APPLICATION=amgtar
  sendbackup: info RECOVER_CMD=/usr/bin/gzip -dc |/usr/libexec/amanda/application/amgtar restore [./file-to-restore]+
  sendbackup: info COMPRESS_SUFFIX=.gz
  sendbackup: info end
  | Total bytes written: 10240 (10KiB, 11MiB/s)
  sendbackup: size 10
  sendbackup: end
  |
  ? Script 'amlvm-snapshot' command 'POST-DLE-BACKUP' exited with status 1: see /var/log/amanda/client/daily/sendbackup.20110209144427.debug
  --------

amlvm-snapshot debug file:

Wed Feb  9 16:06:03 2011: Amlvm_snapshot: pid 6003 ruid 5002 euid 5002 version 3.2.1:
 start at Wed Feb  9 16:06:03 2011
Wed Feb  9 16:06:03 2011: Amlvm_snapshot: pid 6003 ruid 5002 euid 5002 version 3.2.1:
 rename at Wed Feb  9 16:06:03 2011
Wed Feb  9 16:06:03 2011: Amlvm_snapshot: script: Amlvm_snapshot

Wed Feb  9 16:06:03 2011: Amlvm_snapshot: command: post_dle_backup
Wed Feb  9 16:06:03 2011: Amlvm_snapshot: warning: Argument "Failed to execute (statu
s 256) `sudo /usr/sbin/lvdisplay..." isn't numeric in numeric ne (!=) at /usr/lib/per
l5/site_perl/5.8.8/Amanda/Script_App.pm line 101.

I have two perl programs installed on the client side - a original perl from Linux distribution which is x86_64 in /usr/bin; a compiled perl from source which is i386 in /usr/local/bin. I changed the amlvm-snapshot program to just include /usr/bin in PATH but still not successful. I can't see the problem from above debug files.

$ENV{'PATH'} = "/sbin:/usr/sbin:/usr/bin";

Client host is CentOS 5

**Comment by marxarelli** [comment] 2013-05-16 05:25
Duplicate of #2.

**Closed as completed by marxarelli** 2013-05-16 05:25 UTC
